// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJutDzVfdJUR9OkghaSOKPAcsjiB8127g',
    appId: '1:417029349546:web:26f885e5cbbdbe77b7f0d3',
    messagingSenderId: '417029349546',
    projectId: 'bookly-app-f7382',
    authDomain: 'bookly-app-f7382.firebaseapp.com',
    storageBucket: 'bookly-app-f7382.firebasestorage.app',
    measurementId: 'G-K7VVGWC4KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnePq44R-HLBUD5NkZVR2x4s83JOQR63s',
    appId: '1:417029349546:android:e561925244c1072cb7f0d3',
    messagingSenderId: '417029349546',
    projectId: 'bookly-app-f7382',
    storageBucket: 'bookly-app-f7382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPL-Jw7MAeEtR0KF9trCKMvp5RsVuDOA0',
    appId: '1:417029349546:ios:52134c2ad4cf6997b7f0d3',
    messagingSenderId: '417029349546',
    projectId: 'bookly-app-f7382',
    storageBucket: 'bookly-app-f7382.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPL-Jw7MAeEtR0KF9trCKMvp5RsVuDOA0',
    appId: '1:417029349546:ios:52134c2ad4cf6997b7f0d3',
    messagingSenderId: '417029349546',
    projectId: 'bookly-app-f7382',
    storageBucket: 'bookly-app-f7382.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJutDzVfdJUR9OkghaSOKPAcsjiB8127g',
    appId: '1:417029349546:web:f059ff700e9e43a8b7f0d3',
    messagingSenderId: '417029349546',
    projectId: 'bookly-app-f7382',
    authDomain: 'bookly-app-f7382.firebaseapp.com',
    storageBucket: 'bookly-app-f7382.firebasestorage.app',
    measurementId: 'G-5Y0HLHF2VR',
  );
}
